name: CodeClique

x-logging: &default-logging
  driver: "local"
  options:
    max-size: 10m
    max-file: "3"

services:
  proxy:
    volumes:
      - ./proxy/nginx.prod.conf:/etc/nginx/conf.d/default.conf:ro
      - /etc/letsencrypt/live/codeclique.fr/fullchain.pem:/etc/nginx/certificates/fullchain.pem:ro
      - /etc/letsencrypt/live/codeclique.fr/privkey.pem:/etc/nginx/certificates/privkey.pem:ro
    image: nginx:mainline-al
    restart: unless-stopped
    logging: *default-logging

  db:
    restart: unless-stopped
    logging: *default-logging

  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    logging: *default-logging

  backend:
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    logging: *default-logging

